In [1]:
import numpy as np

<b>Zeros</b>

Verilen shape ve veritipine göre 0'lardan oluşan bir matris oluşturur. Buradaki shape 1, (3,3), (3,3,3,...,) şeklinde olabilir

In [2]:
np.zeros(shape=(3,3,1),dtype=np.uint8)

array([[[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]]], dtype=uint8)

<b>Full</b>

Verilen shape ve veritipine göre verilen değer ile doldurulmuş bir matris oluşturur.

In [3]:
np.full(shape=(2,2),fill_value="Selam")

array([['Selam', 'Selam'],
       ['Selam', 'Selam']], dtype='<U5')

<b>Arange</b>

start değerinden stop değerine kadar step kadar arttırımla giderek bir dizi oluşturur. Stop noktası dahil değil

In [4]:
np.arange(start=0,stop=1,step=0.2) # baslangic, bitis, adimBuyuklugu ---- Bitis noktasi dahil olmaz

array([0. , 0.2, 0.4, 0.6, 0.8])

<b>Linspace</b>

Start ve Stop arasını num kadar parçaya böler

In [5]:
np.linspace(start=0,stop=1,num=5,endpoint=True) #endpoint True oldugu icin onu da aldı. (stop-start)/(n-1)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
np.linspace(start=0,stop=1,num=5,endpoint=False) #endpoint True oldugu icin onu da aldı. (stop-start)/(n)

array([0. , 0.2, 0.4, 0.6, 0.8])

<b>Rand</b>

0 ile 1 arasında(1 dahil değil) rastgele sayılar oluşturur

In [7]:
np.random.rand(2,3,5) #parametreler x,y,z,... şeklinde gidebilir. Shape'i temsil etmektedir

array([[[0.98752084, 0.10350225, 0.68598892, 0.84897079, 0.16391109],
        [0.23969248, 0.75937256, 0.50189784, 0.32789032, 0.9544414 ],
        [0.95719767, 0.10644583, 0.85912202, 0.85841225, 0.51761515]],

       [[0.94469534, 0.56912427, 0.00614025, 0.02726533, 0.0176915 ],
        [0.17532766, 0.9258776 , 0.47085068, 0.01059849, 0.98467062],
        [0.8064586 , 0.69868626, 0.13009638, 0.81250465, 0.37246153]]])

<b>Randn</b>

Normal dağılıma sahip, ortalaması sıfır olan ve standart sapması 1 olan bir rastgele dizi oluşturur. Negatif değerlerin de olduğuna dikkat edelim

In [8]:
np.random.randn(2,3,5) #parametreler x,y,z,... şeklinde gidebilir. Shape'i temsil etmektedir

array([[[-1.10806661,  0.84859225, -0.1410087 , -0.53797115,
         -0.99680723],
        [-0.32392945, -0.39324472, -0.92195357, -1.02599716,
          1.22665726],
        [-1.27803255, -0.07002232, -0.08385523, -0.31042656,
         -1.75166   ]],

       [[ 0.55040344,  0.33209366, -0.58558821, -0.51739286,
          1.05676958],
        [ 0.38701967, -1.70999385, -2.75688992, -1.11051506,
         -0.32813361],
        [ 0.03950435,  1.08870608, -1.41120245,  0.74904149,
         -0.01722248]]])

<b>Randint</b>

low ve high(high dahil degil) parametreleri arasında size boyutunda rastgele tamsayılardan oluşan bir matris oluşturur.

In [9]:
np.random.randint(low=0,high=10,size=(3,5))

array([[9, 5, 2, 3, 8],
       [8, 8, 6, 3, 1],
       [0, 5, 8, 8, 5]])

<b>np.dtype</b>

Dizideki elemanların hangi veri tipinden olduğunu gösterir

In [10]:
dizi = np.zeros(shape=(2,2),dtype=np.uint32)

dizi.dtype

dtype('uint32')

<b>np.itemsize</b>

Dizideki her bir elamanın kaç byte yer kapladığını gösterir

In [11]:
dizi = np.zeros(shape=(2,2),dtype=np.float)

dizi.itemsize

8

<b>np.ndim : </b> Dizinin boyut sayısını verir. Sadece dönüş yapar.<br/>
<b>np.shape : </b> Dizinin şeklini verir. Ayrıca değiştirebilirdir.<br/>
<b>np.reshape : </b> Dizinin şeklini değiştiren fonksiyondur. np.shape ile de aynı işlem yapılabilir. <br/>
<b>np.ravel : </b> Çok boyutlu bir diziyi, vektöre çevirir. Düzleştirir(flattening).<br/>
<b>np.resize : </b> Dizinin şeklini değiştirir. reshape metodundan farklı olarak şekli değiştirilecek diziye metottan dönen değeri atamaya gerek yoktur(inplace=True misali).

In [12]:
dizi = np.random.randint(low=0,high=50,size=(5,5))

In [13]:
dizi.ndim

2

In [14]:
dizi.shape

(5, 5)

In [15]:
dizi.shape = 25
dizi.shape

(25,)

In [16]:
dizi = dizi.reshape((5,5)) #parametre olarak dönüştürülmek istenen shape'i alır.
dizi.shape

(5, 5)

In [17]:
dizi = dizi.ravel()
dizi.shape

(25,)

<b>np.sum()</b>

In [10]:
a = np.array([[3,2,6],[1,3,0],[8,5,1]])
a

array([[3, 2, 6],
       [1, 3, 0],
       [8, 5, 1]])

In [11]:
#a.sum(axis=None)
a.sum() #tüm elemanları toplamı

29

In [12]:
a.sum(axis=0)#satırların toplamını verir

array([12, 10,  7])

In [13]:
a.sum(axis=1)#sutünların toplamını verir

array([11,  4, 14])

<b>Dizilere Erişim<b/>

In [18]:
dizi = np.random.randint(0,20,10)
dizi

array([ 1, 19, 12, 17,  3, 12, 10,  8,  6, 19])

In [19]:
dizi[:-1] #son eleman hariç tüm elemanlar

array([ 1, 19, 12, 17,  3, 12, 10,  8,  6])

In [20]:
dizi[-1:] #sadece son eleman

array([19])

In [21]:
dizi[1:] #ilk eleman hariç hepsi

array([19, 12, 17,  3, 12, 10,  8,  6, 19])

In [22]:
dizi[::2] #ikiser ikiser atlayarak

array([ 1, 12,  3, 10,  6])

In [23]:
dizi[::-1] #diziyi tersten yazdir

array([19,  6,  8, 10, 12,  3, 17, 12, 19,  1])

In [24]:
dizi[5:-1] #beşinci elemandan başlayarak -1. elemana kadar hepsini al

array([12, 10,  8,  6])

In [25]:
dizi[5:-3] #beşinci elemandan başlayarak -3. elemana kadar hepsini al

array([12, 10])

In [2]:
dizi2 = np.random.randint(0,20,(3,3))
dizi2

array([[ 4,  2, 13],
       [18,  4,  4],
       [14, 15,  0]])

In [4]:
# (0,1) ve (2,1) elemanlarını alıp bunu np.array olarak döndür
dizi2[(0,2),(1,1)] #ilk tuple ile 2. tuple'ın elemanları zip ediliyor gibi düşünlebilir

array([ 2, 15])

<b>Numpy arraylarda atama/değiştirme<b/>

In [26]:
dizi = np.array([3,5,-1,7,11,14,0])

In [27]:
dilim = dizi[:2] #ilk 2 elemani al
dilim

array([3, 5])

In [28]:
dilim[:] = 33 #dizideki tüm elemanlara 33 değerini ata
dilim

array([33, 33])

In [29]:
dizi 

array([33, 33, -1,  7, 11, 14,  0])

Dilimi olusturdugumuz orijinal dizide de aynı değişikler oldu. Yani dilim = dizi[:2] atamasi ile bir referans etme gerçekleşti diyebiliriz. Bunu istemiyorsak <b>copy</b> metodunu kullanabiliriz.

In [30]:
dizi = np.array([3,5,-1,7,11,14,0])
dizi

array([ 3,  5, -1,  7, 11, 14,  0])

In [31]:
dilim = dizi[:2].copy()
dilim

array([3, 5])

In [32]:
dilim[:] = 33
dilim

array([33, 33])

In [33]:
dizi

array([ 3,  5, -1,  7, 11, 14,  0])

In [12]:
dizi = np.random.randn(3,3,3)

In [13]:
dizi

array([[[-0.30430157, -0.05743656, -0.82290489],
        [ 1.12485697, -1.27954464, -0.0275444 ],
        [-0.95100658,  0.12120974, -0.30442654]],

       [[ 1.57179419, -0.4855432 , -0.41179977],
        [ 2.10951617,  0.13907198, -0.34701787],
        [-0.46734731,  0.85602627,  0.81399007]],

       [[ 1.69940718,  0.51220914, -2.05014511],
        [ 0.06691721, -1.12930092,  1.08583411],
        [ 1.35662458, -2.13520625,  1.50427024]]])

In [18]:
dizi[0,0,0]

-0.3043015745401679

In [19]:
dizi[0][0][0]

-0.3043015745401679

In [21]:
dizi[:][:][:]

array([[[-0.30430157, -0.05743656, -0.82290489],
        [ 1.12485697, -1.27954464, -0.0275444 ],
        [-0.95100658,  0.12120974, -0.30442654]],

       [[ 1.57179419, -0.4855432 , -0.41179977],
        [ 2.10951617,  0.13907198, -0.34701787],
        [-0.46734731,  0.85602627,  0.81399007]],

       [[ 1.69940718,  0.51220914, -2.05014511],
        [ 0.06691721, -1.12930092,  1.08583411],
        [ 1.35662458, -2.13520625,  1.50427024]]])

In [22]:
dizi[:,:,:]

array([[[-0.30430157, -0.05743656, -0.82290489],
        [ 1.12485697, -1.27954464, -0.0275444 ],
        [-0.95100658,  0.12120974, -0.30442654]],

       [[ 1.57179419, -0.4855432 , -0.41179977],
        [ 2.10951617,  0.13907198, -0.34701787],
        [-0.46734731,  0.85602627,  0.81399007]],

       [[ 1.69940718,  0.51220914, -2.05014511],
        [ 0.06691721, -1.12930092,  1.08583411],
        [ 1.35662458, -2.13520625,  1.50427024]]])

In [26]:
liste = list([[0,1,2],[3,4,5],[6,7,8]])

In [27]:
liste

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [38]:
liste[0][2]

2

<b>Notlar:</b><br/>
Numpy dizilerinde hem dizi[][].. hem de dizi[a,b,c..] kullanımı mevcut<br/>
Python listelerinde sadece liste[][]... kullanımı mevcut<br/>
np.multiply ve "*" eleman bazında çarpım yapar.<br/>
np.dot, np.matmul ve "@" ise matris çarpımı yapar

<b>Maksimum-Minimum Değerin indeksini bulma</b>

In [2]:
a = np.array([[6,1,5],[3,11,1],[6,7,2]])
a

array([[ 6,  1,  5],
       [ 3, 11,  1],
       [ 6,  7,  2]])

In [3]:
np.argmax(a) #matrisi düzleştirip indeksi dönüyor

4

In [4]:
#bu düz indeksi tekrar orijinal haline getirmek için np.unravel_index'i kullanıyoruz
np.unravel_index(indices=np.argmax(a),shape=a.shape)

(1, 1)

In [5]:
#satırlardaki en büyük elemanları bulma
np.argmax(a,axis=0) #ilk sütundaki tüm elemanları yani tüm satırlardaki elemanlardan en büyüğünün indisini bulur
#bunu diğer sutünlar için tekrarlar

array([0, 1, 0], dtype=int64)

In [6]:
np.argmax(a,axis=1)#sutünlardaki en büyük elemanları bulma

array([0, 1, 1], dtype=int64)

In [7]:
np.max(a,axis=0)

array([ 6, 11,  5])

In [8]:
np.max(a,axis=1)

array([ 6, 11,  7])

<b>Matris Birleştirme</b>

In [14]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [15]:
a

array([[1, 2],
       [3, 4]])

In [16]:
b

array([[5, 6],
       [7, 8]])

<li>Alt alta ekleme</li>

In [18]:
np.concatenate((a,b)) #varsayılan olarak axis = 0 olduğu için alt alta birleştirdi

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
np.vstack((a,b)) #yukarıdaki ile aynı işi yapar(alt alta ekleme).

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.row_stack((a,b))#satırları birleştir

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
np.r_[a,b] #diğerlerinden farklı olarak bu bir fonksiyon değil

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<li>Yan yana ekleme</li>

In [20]:
np.concatenate((a,b),axis=1) #axis=1 olduğu için yan yana ekledi

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [22]:
np.hstack((a,b)) #yukarıdaki ile aynı işi yapıyor(yan yana ekleme)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
np.column_stack((a,b)) #sutünları birleştir

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
np.c_[a,b] #sutünları birleştirir. Diğerlerinden farklı olarak bir fonksiyon değil

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

<b>Matrisleri Ayırma(Split)</b>

In [43]:
a = np.array([[1,2,3],[3,4,7]])

In [31]:
a

array([[1, 2, 3],
       [3, 4, 7]])

<li>Satır Ayırma</li>

In [41]:
x,y = np.split(a,[1]) #1.indisten sonra(varsayılan olan axis=0 yani 1.indisteki satırdan sonra) diziyi ayır
print(x)
print(y)

[[1 2 3]]
[[3 4 7]]


In [51]:
x,y = np.vsplit(a,[1]) #yukarıdaki ile aynı işi yapar
print(x)
print(y)

[[1 2 3]]
[[3 4 7]]


<li>Sutün Ayırma</li>

In [46]:
a

array([[1, 2, 3],
       [3, 4, 7]])

In [47]:
x,y = np.split(a,[1],axis=1)
print(x)
print(y)

[[1]
 [3]]
[[2 3]
 [4 7]]


In [49]:
x,y = np.hsplit(a,[1])
print(x)
print(y)

[[1]
 [3]]
[[2 3]
 [4 7]]
